### ISSUE TITLE
IPython 5.0 breaks ipdb colors, completions

### ISSUE THREAD

**Issue by ngoldbaum** [gotcha/ipdb#100]
It looks like the soon-to-be released IPython 5.0 is going to break ipdb. IPython 5.0 uses prompt_toolkit rather than readline.

**Comment by gotcha** [comment]
Thanks for the heads up. I'll check asap. In the meanwhile, PR are welcome

**Comment by takluyver** [comment]
See ipython/ipython#9487 - `IPython.core.debugger` is now plainer, and the completion functionality is moved to `IPython.terminal.debugger` (and as @ngoldbaum says, it now uses PTK instead of readline). Sorry for breaking the API, but we needed to separate them so that IPython.core.debugger can still work inside the notebook and other Jupyter clients.
