### ISSUE TITLE
ipdb autocompleter should be able to use "readlinelike" completions

### ISSUE THREAD

**Issue by ferdynice** [gotcha/ipdb#118]
It would be nice to have a configuration option for ipdb to have the autocompleter use the "old style readlinelike" completions.

Please have a look at http://ipython.readthedocs.io/en/stable/config/options/terminal.html for how IPython solves this:

```
TerminalInteractiveShell.display_completions : ‘column’|’multicolumn’|’readlinelike’
    Default: 'multicolumn'
```

**Comment by gnebehay** [comment]
I tend to believe that this is an IPython issue. It can be reproduced without ever using ipdb
```
$ ipython
Python 3.5.3rc1 (default, Jan  3 2017, 04:40:57) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: TkAgg

In [1]: abc={}

abc.<TAB> *shows multicolumn suggestions*

In [2]: a=b
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-6aea67367311> in <module>()
----> 1 a=b

NameError: name 'b' is not defined

In [3]: %debug
> <ipython-input-5-6aea67367311>(1)<module>()
----> 1 a=b

ipdb> abc.<TAB> *shows one-column suggestions*
```
Would you mind to post this to https://github.com/ipython/ipython ?

**Comment by ferdynice** [comment]
Not sure if I understand. This feature can be configured with some ipython config. (See first post).

Afaik, ipdb should add config to be able to set that ipython config.

I probably lack understanding how ipython is used exactly. Feel free to elaborate.

**Comment by gnebehay** [comment]
The main point is that this github project (ipdb) is merely a wrapper module that makes it easier to call the IPython debugger. As soon as `ipdb.set_trace()` is called, we hand processing over to the IPython debugger. 

If I understand your issue correctly, you would like the completion style of the debugger to be changed. I had assumed that the IPython debugger would be already using `TerminalInteractiveShell.display_completions` but apparently this is not the case. Correct me if I am wrong, but as far as I can see you currently don't know how to achieve the desired behavior. 

We could try and fiddle with the configuration of the IPython debugger, but I feel this should actually be solved in the IPython project itself, so that other people benefit from it.

**Comment by ferdynice** [comment]
Ok I think I understand your point: The debugger is a distinctive part of IPython. It seems like this debugger does seem to pick up the configuration line
`c.TerminalInteractiveShell.display_completions = 'readlinelike`
in
`~/.ipython/profile_default/ipython_config.py`.

If that's indeed what mean, feel free to close this and I will bring it up with the IPython project.

**Comment by ferdynice** [comment]
(just to clarify: I have edited my last post)

**Comment by gnebehay** [comment]
Yup, thx! I'll leave this one open just so that we can track upstream progress.

**Comment by gnebehay** [comment]
Would you mind to update to IPython 5.3 and see if it works now?

**Comment by gnebehay** [comment]
Yes, I think it is actually fine now.
